#!/usr/bin/env bash
set -e
pwd
trap 'rm -f ./instance.sbom.json' EXIT
echo '{}' > ./instance.sbom.json

echo "Found .npmrc at: $npmrc_path"

# Modify Docker build to use tokens
# To debug it helps to use:  --no-cache \

docker build \
    --no-cache \
    --progress=plain \
    -f Dockerfile.build \
    -t telicent-paralog-intermediate \
    --load . \
    && \
    docker build \
    --no-cache \
    --progress=plain \
    -f Dockerfile \
    --build-arg BASE_IMAGE=telicent-paralog-intermediate \
    --build-arg APP_NAME=telicent-paralog \
    -t telicent-paralog-local \
    --load . \
    && \
    docker images | grep telicent-paralog-local
