#!/usr/bin/env bash
set -e
pwd
trap 'rm -f ./paralog.sbom.json' EXIT
echo '{}' > ./paralog.sbom.json


# Modify Docker build to use tokens
# To debug it helps to use:  --no-cache \



docker build \
    --progress=plain \
    -f Dockerfile.build \
    -t telicent-paralog-intermediate \
    --load . \
    && \
    docker build \
    --no-cache \
    --progress=plain \
    -f Dockerfile.offline \
    --build-arg BASE_IMAGE=telicent-paralog-intermediate \
    --build-arg APP_NAME=telicent-paralog \
    -t telicent-paralog-offline-local \
    --load . \
    && \
    docker images | grep telicent-paralog-offline-local
