#!/usr/bin/env bash
set -e

source ./scripts/utils.app-config-json
# Note: The above sets:
# - $app_name
# - $repo_name
# - $image_sbom_json

source ./scripts/utils.docker-image-names
# Note: The above sets:
# - $image_run 

#app_sbom_json="$app_name.sbom.json"


# Setup trap to handle all script terminations
cleanup() {
  rm -f "./${app_name}.sbom.json"
}
trap cleanup EXIT
echo "{}" > "./${app_name}.sbom.json"

trivy image --download-db-only

export FONT_AWESOME_TOKEN=$(UNMASK=true yarn --silent tefe npmrc-authtoken //npm.fontawesome.com/)
if [[ -z "$FONT_AWESOME_TOKEN" ]]; then
  echo "Necessary tokens not found in .npmrc, cannot proceed with build."
  exit 1
fi
if [[ -z "$app_name" || -z "$repo_name" ]]; then
  echo "Necessary config found, cannot proceed with build."
  exit 1
fi

echo "APP_NAME=$app_name"

yarn install
yarn build

echo "image_run: $image_run"
docker build \
    --no-cache \
    --progress=plain \
    -f Dockerfile \
    -t "$image_run" \
    --build-arg APP_NAME="$app_name" \
    --load .;

./scripts/utils.scan "$image_run";