name: Publish new release version

on:
  push:
    branches:
      - "main"

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          prerelease: false
